### ISSUE TITLE
Google Maps API twice error due to two modules

### ISSUE THREAD

**Issue by skeletorkun** [jmsardina/location-autocomplete#10]
It s more of a generic error actually, but i m using this module along with [react-google-maps](https://github.com/tomchentw/react-google-maps ) 

On page load, I receive the infamous:

"You have included the Google Maps API multiple times on this page. This may cause unexpected errors."
To repeat, I am using maps via modules and not by directly including <script> tags. What is the best way to overcome such cases?

**Comment by jmsardina** [comment]
@skeletorkun 
I took a look at `react-google-maps`, and I assume you're using the `withScriptsJs` component if you're not manually adding the `<script />` tag on the header.

That component works leveraging the [`scriptjs`](https://github.com/ded/script.js) package to dynamically create a `<script />` tag for the Google Maps library and inserting it into the DOM.

`location-autocomplete` tries to prevent multiple scripts from being added by checking if another instance of the component exists already.  I realize this is not a good solution because it does not account for scripts added by a third party (i.e. `react-google-maps` in your case).

We can remove the scope of this check so that it takes other instances of this script into consideration.

**Comment by jmsardina** [comment]
@skeletorkun I updated the package to prevent the import of the Google Maps library if a script already exists on the DOM (even if it's not done loading yet).

However, as documented in the updated README, other packages can still import the Google Maps library later on (after `location-autocomplete` has already inserted the script tag to the DOM), which will result in the same warning.
